name: Daily Job Runner

on:
  #自动清理：每天早上6点
  schedule:
    - cron: 0 22 * * *
  #手动清理
  workflow_dispatch:

permissions: write-all

jobs:
  run-daily:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
        
      - name: Initialization Values
        run: |
          echo "WRT_DATE=$(TZ=UTC-8 date +"%y.%m.%d-%H.%M.%S")" >> $GITHUB_ENV
          
      - name: Setup workspace
        run: |
          cd wsdaily_linux_amd64
          chmod +x wsdaily
          
      - name: Generate config
          sed -i "s/__LOGIN1__/${{ secrets.WAMUD_LOGIN1}}/g" wsdaily_linux_amd64/conf.yaml
          sed -i "s/__PASSWORD1__/${{ secrets.WAMUD_PASSWORD1}}/g" wsdaily_linux_amd64/conf.yaml
          sed -i "s/__LOGIN2__/${{ secrets.WAMUD_LOGIN2}}/g" wsdaily_linux_amd64/conf.yaml
          sed -i "s/__PASSWORD2__/${{ secrets.WAMUD_PASSWORD2}}/g" wsdaily_linux_amd64/conf.yaml
          sed -i "s/__LOGIN3__/${{ secrets.WAMUD_LOGIN3}}/g" wsdaily_linux_amd64/conf.yaml
          sed -i "s/__PASSWORD3__/${{ secrets.WAMUD_PASSWORD3}}/g" wsdaily_linux_amd64/conf.yaml
          sed -i "s/__LOGIN4__/${{ secrets.WAMUD_LOGIN4}}/g" wsdaily_linux_amd64/conf.yaml
          sed -i "s/__PASSWORD4__/${{ secrets.WAMUD_PASSWORD4}}/g" wsdaily_linux_amd64/conf.yaml
          sed -i "s/__LOGIN5__/${{ secrets.WAMUD_LOGIN5}}/g" wsdaily_linux_amd64/conf.yaml
          sed -i "s/__PASSWORD5__/${{ secrets.WAMUD_PASSWORD5}}/g" wsdaily_linux_amd64/conf.yaml
          
      - name: Execute daily task
        run: ./wsdaily --mode > run output.log
        working-directory: ./wsdaily_linux_amd64
        
      - name: Upload firmware directory
        uses: actions/upload-artifact@main
        with:
          name: ${{ env.WRT_DATE }}
          path: ./wsdaily_linux_amd64/