name: Daily Job Runner

on:
  #自动清理：每天早上6点
  schedule:
    - cron: 0 22 * * *
  #手动清理
  workflow_dispatch:

permissions: write-all

jobs:
  run-daily:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
        
      - name: Initialization Values
        run: |
          echo "WRT_DATE=$(TZ=UTC-8 date +"%y.%m.%d-%H.%M.%S")" >> $GITHUB_ENV
          
      - name: Setup workspace
        run: |
          cd wsdaily_linux_amd64
          chmod +x wsdaily
          
      - name: Execute daily task
        run: ./wsdaily --mode > run output.log
        working-directory: ./wsdaily_linux_amd64
        
      - name: Upload firmware directory
        uses: actions/upload-artifact@main
        with:
          name: ${{ env.WRT_DATE }}
          path: ./wrt/upload/        